---
- name: Lowering security for a specific container by making changes into DeploymentConfig
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
     - serviceaccount: salowersecurity
  tasks:
    - fail: msg="deploymentconfig is not defined"
      when: deploymentconfig is not defined
      tags:
         - always

    - fail: msg="namespace is not defined"
      when: namespace is not defined
      tags:
         - always

    - name: "Create a Service Account named: {{ serviceaccount }}"
      command: oc create serviceaccount {{ serviceaccount }} --namespace {{ namespace }}

    - name: "Allow this pod to run in a relax Security Context"
      command: oc adm policy add-scc-to-user anyuid --serviceaccount {{ serviceaccount }} --namespace {{ namespace }}

    - name: "Allow this pod to run in a Privileged Security Context"
      command: oc adm policy add-scc-to-user privileged system:serviceaccount:{{ namespace }}:{{ serviceaccount }}

    - name: "Patch DeploymentConfig {{ deploymentconfig }} to run under a privileged container"
      command: oc patch deploymentconfig/{{ deploymentconfig }} --patch '{"spec"{{ ':' }}{"template"{{ ':' }}{"spec"{{ ':' }} {"containers"{{ ':' }} [{"name"{{ ':' }}"{{ deploymentconfig }}","securityContext"{{ ':' }} {"privileged"{{ ':' }} true}} ],"serviceAccountName"{{ ':' }}"{{ serviceaccount }}"}}}}' --namespace {{ namespace }}
