---
- name: "NODE: Prefetching Docker Images from a file"
  hosts: nodes
  gather_facts: False
  tasks:
     - name: "Please set property: node_tar_file"
       fail: "msg='Please set property: node_tar_file'"
       when: node_tar_file is not defined or node_tar_file is none

     - name: "Gathering file facts: {{ node_tar_file }}"
       local_action: stat path={{ node_tar_file }}
       register: file_status

     - name: "Does it exist file ? {{ node_tar_file }}"
       fail: msg="File {{ node_tar_file }} does not exists"
       when: not file_status.stat.exists|bool

     - name: "Copying file: {{ node_tar_file }}"
       copy: src={{ node_tar_file }} dest=/root

     - name: Start Docker Service
       service: name=docker state=started

     - name: Loading images from this file
       command: docker load --input=/root/{{ node_tar_file }}
