apiVersion: v1
kind: BuildConfig
metadata:
  name: deploy-green
spec:
  triggers:
    - type: GitHub
      github:
        secret: githubtasks
    - type: Generic
      generic:
        secret: generictasks
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('maven') {
           stage ('Build') {
             git 'http://gogs:3000/demo/openshift-tasks-testdrive'
             sh "mvn clean install -s configuration/cicd-settings.xml -DskipTests=true"
           }
   
           stage('Deploy') {
             sh "oc project bluegreen-example"
             sh "oc start-build tasks-green-app --from-file target/openshift-tasks.war --follow --wait=true -n bluegreen-example"
           }
        }
    type: JenkinsPipeline
    type: Generic
status:
  lastVersion: 0
