apiVersion: v1
kind: BuildConfig
metadata:
  name: switch-to-blue
spec:
  triggers:
    - type: GitHub
      github:
        secret: githubtasks
    - type: Generic
      generic:
        secret: generictasks
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node {
           stage('Release') {
              sh "oc patch route/tasks --patch '{\"spec\":{\"to\":{\"name\":\"tasks-blue-app\"}}}' -n bluegreen-example"
           }
        }
    type: JenkinsPipeline
    type: Generic
status:
  lastVersion: 0
